FROM w251/tensorrtlab05:dev-tx2-4.2_b158

RUN apt update

ENV DEBIAN_FRONTEND=noninteractive

RUN apt install -y python-pip vim-tiny mosquitto-clients python3-opencv

RUN pip3 install --upgrade pip

RUN pip3 install paho-mqtt


EXPOSE 1883

WORKDIR /
COPY faces.py .

CMD python3 faces.py
