FROM w251/keras:dev-tx2-4.2_b158-py3

RUN git clone --recursive https://github.com/NVIDIA-Jetson/tf_trt_models.git

WORKDIR tf_trt_models

RUN ./install.sh python3

RUN apt update

ENV DEBIAN_FRONTEND=noninteractive

RUN apt install -y python-opencv python-pip vim-tiny mosquitto-clients libopencv-dev

RUN pip install paho-mqtt

EXPOSE 1883

WORKDIR /
COPY faces.py .

CMD python faces.py
