FROM ubuntu

RUN apt update

ENV DEBIAN_FRONTEND=noninteractive

RUN apt install -y python-opencv python-pip vim-tiny mosquitto-clients libopencv-dev

RUN pip install paho-mqtt

WORKDIR /
COPY facedetect.py

CMD python facedetect.py
