FROM ubuntu

RUN apt update

ENV DEBIAN_FRONTEND=noninteractive

RUN apt install -y python-opencv python-pip vim-tiny mosquitto-clients libopencv-dev

RUN pip install paho-mqtt

EXPOSE 1883

#assuming repo cloned at root
WORKDIR /w251-posture/get_data/
COPY * .

CMD python create_db.py
CMD python readandsave.py
